import type { Resume } from "@/lib/resume-types";
import sampleImage from "@/sample.jpg";

export function createMockResume(templateId: string): Resume {
  const baseId = Math.random().toString(36).substr(2, 9);
  
  return {
    id: baseId,
    name: "Sample Resume",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    personal: {
      fullName: "Ian Magistrado Naz",
      title: "Senior Product Designer",
      phone: "(555) 123-4567",
      email: "iannaz1228@gmail.com",
      location: "San Francisco, CA",
      linkedin: "linkedin.com/in/iannaz1228",
      github: "github.com/iannaz1228",
      portfolio: "infosyscoreteam.com",
      website: "infosyscoreteam.com",
      photo: sampleImage,
      photoShape: "circle",
      photoSize: 120,
      showPhoto: true,
      visibility: {
        phone: true,
        email: true,
        location: true,
        linkedin: true,
        github: false,
        portfolio: true,
        website: false,
      },
    },
    summary:
      "Creative and strategic product designer with 6+ years of experience building digital products that users love. Specialized in design systems, user research, and cross-functional collaboration. Passionate about solving complex problems through thoughtful design.",
    experience: [
      {
        id: "exp1",
        company: "Innovate Digital",
        position: "Senior Product Designer",
        location: "San Francisco, CA",
        startDate: "Jan 2022",
        endDate: "Present",
        description:
          "Led design strategy for flagship product serving 2M+ users. Established design system reducing development time by 40%. Mentored junior designers and conducted user research across 5 continents.",
      },
      {
        id: "exp2",
        company: "Creative Studio Co.",
        position: "Product Designer",
        location: "New York, NY",
        startDate: "Jun 2019",
        endDate: "Dec 2021",
        description:
          "Designed customer-facing features and internal tools. Improved user engagement by 35% through iterative design improvements. Collaborated with engineering and product teams on quarterly roadmaps.",
      },
      {
        id: "exp3",
        company: "StartupHub",
        position: "Junior Designer",
        location: "Remote",
        startDate: "Feb 2018",
        endDate: "May 2019",
        description:
          "Created wireframes and prototypes for mobile and web applications. Participated in design sprints and user testing sessions. Built reusable UI components library.",
      },
    ],
    education: [
      {
        id: "edu1",
        school: "University of California, Berkeley",
        degree: "Bachelor of Arts",
        field: "Graphic Design",
        startDate: "2014",
        endDate: "2018",
        gpa: "3.8",
        honors: "Cum Laude",
        showGpa: true,
        showHonors: true,
      },
      {
        id: "edu2",
        school: "Nielsen UX Bootcamp",
        degree: "Certificate",
        field: "User Experience Design",
        startDate: "2017",
        endDate: "2017",
        gpa: "",
        honors: "",
        showGpa: false,
        showHonors: false,
      },
    ],
    projects: [
      {
        id: "proj1",
        name: "Design System v2.0",
        role: "Lead Designer",
        description:
          "Rebuilt company design system from scratch with 150+ components. Improved designer productivity and code consistency across 8 product teams.",
        tech: "Figma, React, TypeScript",
        github: "github.com/innovate/design-system",
        demo: "design-system.innovate.io",
        website: "",
      },
      {
        id: "proj2",
        name: "Mobile Banking App",
        role: "UX/UI Designer",
        description:
          "Designed intuitive interface for financial management app. Conducted extensive user research with 50+ participants. App reached 100K downloads in first month.",
        tech: "Figma, iOS, Usability Testing",
        github: "",
        demo: "apps.apple.com/us/app/bankmate",
        website: "",
      },
    ],
    skills: [
      { id: "skill1", name: "Product Design", level: 95, category: "Core" },
      { id: "skill2", name: "Figma", level: 90, category: "Tools" },
      { id: "skill3", name: "User Research", level: 88, category: "Core" },
      { id: "skill4", name: "Prototyping", level: 92, category: "Core" },
      { id: "skill5", name: "Design Systems", level: 85, category: "Core" },
      { id: "skill6", name: "Adobe XD", level: 80, category: "Tools" },
      { id: "skill7", name: "Wireframing", level: 90, category: "Core" },
      { id: "skill8", name: "Accessibility (WCAG)", level: 82, category: "Core" },
      { id: "skill9", name: "CSS/HTML Basics", level: 75, category: "Technical" },
      { id: "skill10", name: "Data Visualization", level: 78, category: "Core" },
    ],
    certifications: [
      {
        id: "cert1",
        name: "Certified UX Professional",
        org: "User Experience Professionals Association",
        date: "2021",
        url: "uxpa.org",
      },
      {
        id: "cert2",
        name: "Google UX Design Certificate",
        org: "Google",
        date: "2020",
        url: "coursera.org",
      },
    ],
    languages: [
      { id: "lang1", name: "English", proficiency: "Native" },
      { id: "lang2", name: "Spanish", proficiency: "Fluent" },
      { id: "lang3", name: "Mandarin", proficiency: "Intermediate" },
    ],
    references: [
      {
        id: "ref1",
        name: "Dr. Michael Chen",
        position: "VP of Product, Innovate Digital",
        contact: "michael.chen@innovate.io",
      },
      {
        id: "ref2",
        name: "Sarah Williams",
        position: "Design Director, Creative Studio Co.",
        contact: "sarah.w@creativestudio.com",
      },
    ],
    visibility: {
      summary: true,
      experience: true,
      education: true,
      projects: true,
      skills: true,
      certifications: true,
      languages: true,
      references: false,
    },
    sectionOrder: [
      "summary",
      "experience",
      "education",
      "skills",
      "projects",
      "certifications",
      "languages",
      "references",
    ],
    customization: {
      template: (templateId as any) || "modern-developer",
      primaryColor: "#3B82F6",
      accentColor: "#8B5CF6",
      textColor: "#1F2937",
      backgroundColor: "#FFFFFF",
      fontFamily: "Inter",
      fontSize: 11,
      sectionSpacing: 8,
      lineHeight: 1.5,
      skillStyle: "bars",
      showSkillLevels: true,
      referencesMode: "hidden",
    },
  };
}
